/*
 * Macedon.io
 *
 * Macedon.io API 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package macedonio

import (
	"github.com/jinzhu/gorm"
	"time"
)

type User struct {

	Id int64 `json:"id,omitempty"`

	Username string `json:"username,omitempty"`

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`

	// User Status
	UserStatus int32 `json:"userStatus,omitempty"`
}

func AutoMigrateUserSchemas() {
	GetDBHandle().AutoMigrate(&DBUser{})
	GetDBHandle().AutoMigrate(&DBUserToken{})
}

type DBUser struct {
	gorm.Model
	Username string `gorm:"UNIQUE_INDEX"`
	Email string `gorm:"UNIQUE_INDEX"`
	Salt []byte
	SaltedPasswordHash []byte
}

type DBUserToken struct {
	gorm.Model
	Token [16]byte `gorm:"UNIQUE_INDEX"`
	DBUser DBUser
	Scope string
	ExpiresAt time.Time
}