/*
 * Macedon.io
 *
 * Macedon.io API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package macedonio

type Graph struct {
	Id string `json:"id"`

	Nodes []Node `json:"nodes"`

	Tags []Tag `json:"tags,omitempty"`
}
