/*
 * Macedon.io
 *
 * Macedon.io API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package macedonio

type GraphType string

// List of GraphType
const (
	PRIVATE  GraphType = "private"
	SHARED   GraphType = "shared"
	PUBLIC   GraphType = "public"
	TEMPLATE GraphType = "template"
)
