/*
 * Macedon.io
 *
 * Macedon.io API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package macedonio

type Node struct {
	Id string `json:"id"`

	Edges []string `json:"edges"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	X int32 `json:"x,omitempty"`

	Y int32 `json:"y,omitempty"`

	GraphType *GraphType `json:"graphType"`
}
