/*
 * Macedon.io
 *
 * Macedon.io API 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package macedonio

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/macedonio/1.0.0/",
		Index,
	},

	Route{
		"GetConfig",
		strings.ToUpper("Get"),
		"/macedonio/1.0.0/config",
		GetConfig,
	},

	Route{
		"UpdateConfig",
		strings.ToUpper("Post"),
		"/macedonio/1.0.0/config",
		UpdateConfig,
	},

	Route{
		"AddGraph",
		strings.ToUpper("Post"),
		"/macedonio/1.0.0/goal",
		AddGraph,
	},

	Route{
		"GetGraph",
		strings.ToUpper("Get"),
		"/macedonio/1.0.0/goal/{goalID}",
		GetGraph,
	},

	Route{
		"GoalsGet",
		strings.ToUpper("Get"),
		"/macedonio/1.0.0/goals",
		GoalsGet,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/macedonio/1.0.0/user",
		CreateUser,
	},

	Route{
		"CreateUsersWithArrayInput",
		strings.ToUpper("Post"),
		"/macedonio/1.0.0/user/createWithArray",
		CreateUsersWithArrayInput,
	},

	Route{
		"CreateUsersWithListInput",
		strings.ToUpper("Post"),
		"/macedonio/1.0.0/user/createWithList",
		CreateUsersWithListInput,
	},

	Route{
		"DeleteUser",
		strings.ToUpper("Delete"),
		"/macedonio/1.0.0/user/{username}",
		DeleteUser,
	},

	Route{
		"GetUserByName",
		strings.ToUpper("Get"),
		"/macedonio/1.0.0/user/{username}",
		GetUserByName,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Get"),
		"/macedonio/1.0.0/user/login",
		LoginUser,
	},

	Route{
		"LogoutUser",
		strings.ToUpper("Get"),
		"/macedonio/1.0.0/user/logout",
		LogoutUser,
	},

	Route{
		"UpdateUser",
		strings.ToUpper("Put"),
		"/macedonio/1.0.0/user/{username}",
		UpdateUser,
	},
}
