/*
 * Macedon.io
 *
 * Macedon.io API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/piokra/Macedonio/backend/go"
)

func main() {
	log.Printf("Server started")
	if err := sw.InitDBHandle(); err != nil {
		log.Printf("Failed to init db. Err: %v\n", err)
		panic(err)
	}
	sw.AutoMigrateUserSchemas()

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
