/*
 * Macedon.io
 *
 * Macedon.io API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	. "github.com/piokra/macedonio/backend/go"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")
	if err := InitDBHandle(); err != nil {
		log.Printf("Failed to init db. Err: %v\n", err)
		panic(err)
	}
	AutoMigrateUserSchemas()

	router := NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
