version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: Macedonio
      MYSQL_USER: macedonio
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    container_name: macedonio_mysql_integration_db
    ports:
      - 3306:3306

  test:
    depends_on:
      - db
    build:
        context: ../
        dockerfile: Dockerfile-test
    environment:
      MYSQL_HOSTNAME: db
      MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: macedonio_integration_test
